select
    CREATED_AT_DT,
    PLACE,
    LAT,
    LON,
    SUNRISE_AT,
    SUNSET_AT,
    min(TEMP_CELCIUS) as MIN_TEMP_CELCIUS,
    max(TEMP_CELCIUS) as MAX_TEMP_CELCIUS,
    min(TEMP_FEELS_LIKE_CELCIUS) as MIN_FEELS_LIKE_TEMP_CELCIUS,
    max(TEMP_FEELS_LIKE_CELCIUS) as MAX_FEELS_LIKE_TEMP_CELCIUS
from {{ ref('stg_current_weather') }}
group by
    PLACE,
    CREATED_AT_DT,
    LAT,
    LON,
    SUNRISE_AT,
    SUNSET_AT
